name: Empire Radar

on:
  schedule:
    - cron: '*/30 * * * *' # يعمل كل 30 دقيقة
  workflow_dispatch: # يسمح لك بتشغيله يدوياً

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies and Run Script
        run: |
          pip install requests
          python quantum_test.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Update Radar Data [Automated]" || exit 0
          git pull --rebase origin main
          git push origin main