name: Empire Radar

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *' # تشغيل تلقائي كل 30 دقيقة
  workflow_dispatch: # يسمح لك بتشغيله يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Radar
        run: python quantum_test.py
      - name: Commit and Push
        run: |
          git config --global user.name "eissa070"
          git config --global user.email "eissa@empire.com"
          git add data.json
          git commit -m "Radar: Data Harvest Complete" || exit 0
          git push